### ISSUE TITLE
clam options

### ISSUE THREAD

**Issue by laissezfarrell** [timothyryanwalsh/brunnhilde#32]
It would be useful if Brunnhilde accepted options for the clam virus scan. In particular, I'd be interested in seeing --max-scansize=#n and --max-filesize=#n, to optionally get around Clam's default filesize cap for scanning.

**Comment by timothyryanwalsh** [comment]
Thanks for reporting this, farrell. I agree that being able to set max-scansize and max-filesize high would be helpful. Would you want this to be user controlled, or would it be simpler if I set the default values for these variables really high in Brunnhilde? It seems that they exist to prevent DoS attacks, which isn't really so much of a threat in our use case.

**Comment by laissezfarrell** [comment]
I'm not sure I have a clear preference, tbh. 

Now that I am aware of the filesize issue, I'd likely pass fairly high values to each of those variables in most cases (unless I'm confident the objects are all <30 MB). From some other boards (e.g.: [this one](https://superuser.com/questions/1055633/use-clamav-to-scan-large-files)), it looks like there's a cap of 4 GB regardless of what the user sets.

**Comment by timothyryanwalsh** [comment]
Okay, for 1.6.1 I'm implementing a '--largefiles' optional arg which sets max-filesize and max-scansize each to 0 (unlimited)

In addition to the automated tests, I tried it out against a directory with 10GB worth of disk image files (granted, only up to 4GB each). Clamscan with default settings took 7 seconds and only scanned 0.02 MB of data. With '--largefiles', clamscan read 9376.65 MB of data but took a full 9 minutes, 38 seconds. So clearly there's a trade-off here, which is why I'm leaning toward keeping default behavior as it was in 1.6.0.

Thoughts?

**Comment by timothyryanwalsh** [comment]
I've also updated the README accordingly in the 1.6.1 branch and noted the 4GB file size limit for virus scanning, since that's an important thing for people to be aware of.

**Comment by laissezfarrell** [comment]
I think the default behavior as you describe makes sense given the tradeoff you describe. In an ideal world, people running Brunnhilde (or clam as a one-off) would know the file size issues already. Not sure what else you can do other than mention it in the readme.

**Comment by timothyryanwalsh** [comment]
Perfect. Just pushed the release out, so "sudo pip install brunnhilde.py --upgrade" should do the trick for you. Closing the ticket now. Thanks again for reporting the issue!
